# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ravinsu M.H.S - COBSCComp171P-001' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ravinsu M.H.S - COBSCComp171P-001

  target 'Ravinsu M.H.S - COBSCComp171P-001Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ravinsu M.H.S - COBSCComp171P-001UITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	pod 'SwiftyJSON'
	pod 'GoogleSignIn'
	pod 'Alamofire', '~>4.4'
	pod 'Kingfisher', '~> 4.0'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'



end
